name: calc-ci
on: [push, pull_request]
jobs:
  build_calc:
    runs-on: ubuntu-latest
    steps:
      - name: Install python dependencies
        uses: actions/setup-python@v1
      - name: Get latest cmake
        uses: lukka/get-cmake@latest
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Linter check
        run: |
          pip install cpplint
          cpplint --filter=-legal/copyright,-runtime/references --linelength=120 --recursive .
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DFRUIT_USES_BOOST=False
          make
          cd ..
      - name: Test Token
        run: ./bin/testToken
      - name: Test Parser
        run: ./bin/testParser
